name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: default
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build JAR with Docker
      run: |
        mkdir -p ./build/libs
        docker build --target export --output ./build/libs .
        ls -la ./build/libs/

    - name: List built files
      run: |
        echo "Files in build/libs:"
        find ./build/libs -name "*.jar" -type f

    - name: Create staging directory
      run: mkdir -p build/staging-deploy

    - name: Publish to GitHub Packages
      run: ./gradlew publishMavenPublicationToGitHubPackagesRepository -Pversion=${{ steps.get_version.outputs.VERSION }}
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to Maven Central
      run: ./gradlew jreleaserDeploy -Pversion=${{ steps.get_version.outputs.VERSION }}
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
        JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
        JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          ./build/libs/*.jar
          ./build/libs/easyfin-${{ steps.get_version.outputs.VERSION }}-javadoc.jar
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
